In [1]:
!pip3 install mushroom_rl
!git clone https://github.com/gowun/RL_for_reco.git

Collecting mushroom_rl
  Downloading https://files.pythonhosted.org/packages/00/c6/8752704c263e8e20c471cf824a807370f67d70cc897ccd3ea8ec175cb2f4/mushroom_rl-1.4.0-py3-none-any.whl (171kB)
     |████████████████████████████████| 174kB 4.6MB/s
Requirement already satisfied: joblib in /usr/local/lib/python3.6/dist-packages (from mushroom_rl) (0.14.1)
Requirement already satisfied: torch in /usr/local/lib/python3.6/dist-packages (from mushroom_rl) (1.4.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from mushroom_rl) (1.4.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from mushroom_rl) (3.2.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from mushroom_rl) (4.38.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from mushroom_rl) (0.22.2.post1)
Requirement already satisfied: pytest in /usr/local/lib/python3.6/dist-packages (from mushroom_rl) (3.6.4)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.6/dist-packages (from mushroom_rl) (4.1.2.30)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from mushroom_rl) (1.18.2)
Collecting pygame
  Downloading https://files.pythonhosted.org/packages/8e/24/ede6428359f913ed9cd1643dd5533aefeb5a2699cc95bea089de50ead586/pygame-1.9.6-cp36-cp36m-manylinux1_x86_64.whl (11.4MB)
     |████████████████████████████████| 11.4MB 6.1MB/s
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mushroom_rl) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mushroom_rl) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mushroom_rl) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->mushroom_rl) (0.10.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/dist-packages (from pytest->mushroom_rl) (19.3.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.6/dist-packages (from pytest->mushroom_rl) (0.7.1)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.6/dist-packages (from pytest->mushroom_rl) (8.2.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.6/dist-packages (from pytest->mushroom_rl) (1.3.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from pytest->mushroom_rl) (1.8.1)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from pytest->mushroom_rl) (1.12.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from pytest->mushroom_rl) (46.1.3)
Installing collected packages: pygame, mushroom-rl
Successfully installed mushroom-rl-1.4.0 pygame-1.9.6
Cloning into 'RL_for_reco'...
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 70 (delta 22), reused 70 (delta 22), pack-reused 0
Unpacking objects: 100% (70/70), done.

In [2]:
import numpy as np
from RL_for_reco.finiteMDP_for_Reco import Multiple_FMDP_Reco

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html

In [0]:
p = np.random.random_sample([3, 5, 3])
r = np.random.choice([-1, 0, 1], (3, 5, 3))
for i in range(p.shape[0]):
  for j in range(p.shape[1]):
    p[i, j] = p[i, j] / sum(p[i, j])

In [26]:
n_step = 1000
n_episode = 10
algorithms = ['QL'] * n_episode

agents_list = Multiple_FMDP_Reco(n_episode, n_step, algorithms, 5, p, r)

  0%|          | 0/1000 [00:00<?, ?it/s]

 47%|████▋     | 472/1000 [00:00<00:00, 4719.81it/s]

 78%|███████▊  | 780/1000 [00:00<00:00, 4066.89it/s]



  0%|          | 0/1000 [00:00<?, ?it/s]

 45%|████▌     | 453/1000 [00:00<00:00, 4522.80it/s]

 89%|████████▉ | 890/1000 [00:00<00:00, 4475.23it/s]



  0%|          | 0/1000 [00:00<?, ?it/s]

 42%|████▏     | 422/1000 [00:00<00:00, 4215.44it/s]

 90%|████████▉ | 896/1000 [00:00<00:00, 4360.10it/s]



  0%|          | 0/1000 [00:00<?, ?it/s]

 45%|████▍     | 448/1000 [00:00<00:00, 4472.07it/s]

 92%|█████████▏| 917/1000 [00:00<00:00, 4534.04it/s]



  0%|          | 0/1000 [00:00<?, ?it/s]

 33%|███▎      | 326/1000 [00:00<00:00, 3257.67it/s]

 82%|████████▏ | 820/1000 [00:00<00:00, 3627.71it/s]



  0%|          | 0/1000 [00:00<?, ?it/s]

 44%|████▍     | 439/1000 [00:00<00:00, 4384.27it/s]

 75%|███████▍  | 747/1000 [00:00<00:00, 3887.67it/s]



  0%|          | 0/1000 [00:00<?, ?it/s]

 38%|███▊      | 375/1000 [00:00<00:00, 3746.89it/s]

 86%|████████▋ | 864/1000 [00:00<00:00, 4026.72it/s]



  0%|          | 0/1000 [00:00<?, ?it/s]

 44%|████▍     | 444/1000 [00:00<00:00, 4439.20it/s]

 74%|███████▍  | 744/1000 [00:00<00:00, 3878.76it/s]



  0%|          | 0/1000 [00:00<?, ?it/s]

 34%|███▍      | 338/1000 [00:00<00:00, 3379.92it/s]

 76%|███████▌  | 760/1000 [00:00<00:00, 3593.68it/s]



  0%|          | 0/1000 [00:00<?, ?it/s]

 31%|███       | 306/1000 [00:00<00:00, 3057.15it/s]

 74%|███████▎  | 735/1000 [00:00<00:00, 3345.48it/s]

In [27]:
agents_list.mean_epsilons

array([0.05701374, 0.04885397, 0.06711738])

In [31]:
current_states = np.random.choice(range(3), 50)
current_states

array([0, 0, 0, 0, 1, 0, 2, 2, 1, 1, 2, 0, 0, 0, 0, 0, 1, 1, 0, 2, 2, 1,
       1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 0, 2, 1, 2, 1, 1, 0, 1, 2, 0, 1,
       1, 2, 1, 0, 0, 2])

In [32]:
agents_list.draw_action_matrix(current_states)

    current_state  0th_policy  1th_policy  ...  8th_policy  9th_policy  best_policy
0               0           3           2  ...           4           3            4
1               0           3           3  ...           4           3            3
2               0           3           3  ...           4           3            3
3               0           3           3  ...           4           3            3
4               1           0           1  ...           0           2            0
5               0           3           3  ...           4           3            3
6               2           4           2  ...           2           0            4
7               2           4           4  ...           2           4            4
8               1           0           1  ...           0           0            0
9               1           0           1  ...           0           0            3
10              2           4           4  ...           2           4            2
11              0           3           3  ...           4           3            3
12              0           3           3  ...           4           3            3
13              0           3           3  ...           4           3            3
14              0           3           3  ...           4           3            4
15              0           3           3  ...           4           3            3
16              1           0           1  ...           0           0            0
17              1           0           1  ...           0           0            0
18              0           0           3  ...           4           3            3
19              2           4           4  ...           2           0            4
20              2           4           4  ...           2           4            4
21              1           0           1  ...           1           0            1
22              1           4           1  ...           0           0            0
23              2           4           4  ...           2           4            1
24              1           0           1  ...           0           0            0
25              1           0           1  ...           0           0            0
26              1           0           1  ...           0           0            0
27              2           4           4  ...           2           4            1
28              1           0           1  ...           0           0            0
29              2           4           4  ...           2           4            4
30              2           4           4  ...           2           4            4
31              1           0           1  ...           0           0            0
32              2           4           4  ...           2           4            2
33              0           3           1  ...           4           3            3
34              2           4           4  ...           2           4            4
35              1           1           1  ...           0           1            0
36              2           4           4  ...           2           4            4
37              1           0           1  ...           0           0            0
38              1           0           1  ...           0           0            0
39              0           3           3  ...           4           3            3
40              1           0           1  ...           0           0            3
41              2           4           4  ...           2           4            1
42              0           3           3  ...           4           3            3
43              1           0           1  ...           0           0            0
44              1           0           1  ...           0           0            0
45              2           4           4  ...           2           4            4
46              1           0           1  ...           0           0            3
47              0           3           3  ...           4           3            3
48              0           3           3  ...           4           3            3
49              2           4           4  ...           1           4            1

[50 rows x 12 columns]

In [0]:
Qs_list = agents_list.get_Qs_list()

In [34]:
Qs_list[0]

          a0        a1        a2        a3        a4
s0  0.992103  0.585085 -0.081747  1.794348  0.036525
s1  0.878179  0.814723  0.844205 -0.212949  0.038198
s2 -0.121031  1.784523  0.939999  2.250984  2.561102